### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by rmeier11** [amrishdeep/Dragon#1]
Hallo,

are there Evidence-Files for other languages than english? I need them for the german language.

Thanks,

rmeier11

**Comment by i2infinity** [comment]
At this point I don't have evidence files for languages other than English. You could write your own little screen scrapper tool to extract positive and negative reviews from websites and use them as evidence files (I will explain shortly). It is important that the domain of the evidence file data set matches the actual domain on which you plan to do sentiment analysis. For e.g., the evidence file on this repository was built using data from customer reviews on shopping sites, so it is more accurate in classifying product reviews and might not work well on movie reviews.

Here is one way I would go about building the evidence files (For Naive Bayes classifier, the classification only gets as good as the evidence files you have. So I would spend a lot of time gathering the right data set for evidence files)
1.  Using your favorite scripting tool, crawl through a list of shopping websites and create two buckets of data (Positive bucket – Collection of 4 & 5 star reviews; Negative bucket – Collection of 1 & 2 star reviews)
2.  Prune the data set to remove special characters and common words like a, an, the, etc. which would not contribute to the mood of the review
3.  Once you have completed the previous step, building the evidence files is as simple as building the histogram of words in each bucket
4.  An important step is to verify performance of the evidence files and you could do it by comparing the sentiment analysis results from your evidence files to ones from services like uClassify.com

**Comment by rmeier11** [comment]
Hey,

thanks for the reply.
Which Scraper for Amazon Reviews did you take?

**Comment by i2infinity** [comment]
I had to write my own text scrapper, but it will not be open source for obvious reasons
